// ============================================================
// ================ DAFTAR NAMA TAMU ==========================
// ============================================================

const allGuestNames = [

"Bpk. Kades Banyusari",
"Bpk. Pipin Aripin (Kadus 4)",
"Bpk. Udjun (Alm)",
"Kel. Besar Bpk. Momo Rahmat (Alm)",
"Bpk. Uyu Suparyu (Alm) & Ibu Nining Warningsih",
"Bpk. Ayong Sudrajat (Alm) & Ibu Ai Tatih",
"Bpk. Ema Amajun (Jakarta)",
"Bpk. Dadang & Ibu Siti",
"Bpk. Yusup & Ibu Hera",
"Ibu Titin",
"Bpk. Teddy & Popi",
"Bpk. Indra & Rani",

"Bunda ineu",
"Bu nani",
"Bu ani",
"Kel. ote",
"Bi imas",
"Emas/entus",
"Kel mbk",
"Kel senam ramen",
"Alumni raksa negara",
"Sinah",
"Rina",
"Kel. aki hatoma",
"Novi",
"Ibu-ibu 6b kircon",
"Bu yanti",
"Pak umar",
"Entin",
"Fitri",
"Mamah palih",
"Nia",
"Bunda",
"Nopi",
"Mpah roni",
"Ntye",
"Kekey",
"Agus cincin",
"Ai ciwidey",
"HJ.Mulyani",
"Cunayah jakarta",
"Yati margahayu",
"Eli caringin",
"Enung lembang",
"Kades bokun",
"Rahmat",
"Lilis sadu",
"Vicky sadu",
"Dede",
"Juanah",
"Usi cipinang",
"Euis",
"Milah ciwaru",
"Nunung tegal",
"Nyi nira",
"Risma",
"Yayu",
"Denis",
"Dewi",
"Enok",
"Yani",
"Iyan ciwidey",

"Phylon Grup",
"Mabes 92",
"Keretek 92",
"Lembur Panineungan",
"Ikasa",
"Della",
"Arip Jakarta",
"Bang Uway Jakarta",
"Melly Jakarta",
"SAT BODY PT TRISCO",
"Member senam SBW",
"Baraya OBIC JUGIR"

];

// keluarga inti
const familyNames = allGuestNames.slice(0,12);